config/routes.rb
Tond::Application.routes.draw do
  get "top/index"

  devise_for :users

  resources :rooms do
    resources :messages
  end

  root :to => 'top#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  acts_as_paranoid

  attr_accessible :body

  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  acts_as_paranoid

  attr_accessible :name

  has_many :messages
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
# encoding: utf-8
class MessagesController < ApplicationController
  def index
    @room = Room.find(params[:room_id])
    @message = Message.new
    @message.room_id = @room.id
    @channel_id = "room_#{@room.id}_messages"
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.create(params[:message])
    @channel_id = "room_#{@room.id}_messages"

    if @message
      status = 'success'

      Pusher[@channel_id].trigger(
        'create', {
        body: @message.body
      })
    else
      status = 'failure'
    end

    render json: { status: status, data: @message }
  end
end

app/controllers/rooms_controller.rb
# encoding: utf-8
class RoomsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params[:room])
    @room.save!

    redirect_to @room
  end

  def show
    @room = Room.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_footer.html.haml
%footer
  %p &copy; tond 2013

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "tond"
    = csrf_meta_tags
    = yield :header
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    = favicon_link_tag 'favicon.ico'

  %body
    .wrapper
      .navbar.navbar-fluid-top
        .navbar-inner
          .container-fluid
            %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand(href="#") tond
            .container.nav-collapse
              %ul.nav
                %li= link_to "Room", rooms_path
                - if user_signed_in?
                  %li= link_to "ログアウト", destroy_user_session_path, method: :delete
                - else
                  %li= link_to "ログイン", new_user_session_path

      .container.top_start_point
        .container-fluid
          .row-fluid
            -#
              .span3
                .well.sidebar-nav
                  %ul.nav.nav-list
                    %li.nav-header Sidebar
                    %li= link_to "Link 1", "/path1"
                    %li= link_to "Link 2", "/path2"
                    %li= link_to "Link 3", "/path3"
            .span9
              = bootstrap_flash
              = yield
      .push

    .footer.container
      = yield :special_footer
      = render 'layouts/footer'
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/messages/index.html.haml
- content_for :header do
  = javascript_include_tag 'http://js.pusher.com/1.12/pusher.min.js'

#container
  %div{:id => 'channel_id', 'data-channel-id' => @channel_id}
  %div{:id => 'pusher_key', 'data-pusher-key' => Pusher.key}

  %h2= @room.name

  #messages
    %table.table.table-condensed
      - @room.messages.each do |message|
        %tr
          %td= message.body

- content_for :special_footer do
  = form_for @message, url: room_messages_path(@room), remote: true do |f|
    - if @message.errors.any?
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
    .input-append
      = f.text_field :body, class: 'span8'
      = f.submit 'Post', class: 'btn'

app/views/rooms/index.html.haml
%h1
  Rooms

=link_to 'New Room', new_room_path

%ul
  - @rooms.each do |room|
    %li= link_to room.name, room_path(room)

app/views/rooms/new.html.haml
%h1
  Create New Room

= form_for @room do |f|
  - if @room.errors.any?
    %ul
      - @room.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Create'

app/views/rooms/show.html.haml
%h1
  = @room.name

app/views/top/index.html.haml
%h1 Top#index
%p Find me in app/views/top/index.html.erb
- if user_signed_in?
  = link_to "ログアウト", destroy_user_session_path, method: :delete
- else
  = link_to "ログイン", new_user_session_path